name: Build

on:
  push:
    branches-ignore:
      - builds
  pull_request:
    branches-ignore:
      - builds

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "src"

      - name: Checkout builds
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/checkout@master
        with:
          ref: "builds"
          path: "builds"

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make generateUpdaterJson
          mkdir $GITHUB_WORKSPACE/compiled
          cp $GITHUB_WORKSPACE/src/**/build/*.zip $GITHUB_WORKSPACE/compiled
      
      - name: Upload plugins as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugins
          path: compiled

      - name: Push builds
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd $GITHUB_WORKSPACE/builds
          cp $GITHUB_WORKSPACE/compiled .
          cp $GITHUB_WORKSPACE/src/updater.json .
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push
